pimcore:
    documents:
        doc_types:
            definitions:
                60d65fe6-782c-4983-9896-85ec2d324e74:
                    name: 'Portal Engine - Portal Page'
                    group: 'Portal Engine'
                    controller: 'Pimcore\Bundle\PortalEngineBundle\Controller\PortalController::pageAction'
                    template: null
                    type: page
                    priority: 0
                    creationDate: 1661836804
                    modificationDate: 1661836804
                    staticGeneratorEnabled: null
