pimcore:
    documents:
        doc_types:
            definitions:
                7c1f8017-aa4b-4c6c-8e05-108715737a45:
                    name: 'Portal Engine - Content Page'
                    group: 'Portal Engine'
                    controller: 'Pimcore\Bundle\PortalEngineBundle\Controller\PortalController::contentAction'
                    template: null
                    type: page
                    priority: 0
                    creationDate: 1661836804
                    modificationDate: 1661836804
                    staticGeneratorEnabled: null
