pimcore:
    documents:
        doc_types:
            definitions:
                802a4fda-c164-48d0-9589-507aa543fec7:
                    name: 'Portal Engine - Data Pool Language Variant'
                    group: 'Portal Engine'
                    controller: 'Pimcore\Bundle\PortalEngineBundle\Controller\LanguageVariantController::dataPoolLanguageVariantAction'
                    template: null
                    type: page
                    priority: 0
                    creationDate: 1661836804
                    modificationDate: 1661836804
                    staticGeneratorEnabled: null
